# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
plugins:
  - jekyll-paginate
  - redcarpet
  - jekyll-gist

# Setup
title:            Colleen Smith
tagline:          ''
description:      'A blog about Data Science and sometimes cats.'
url:              http://6cdds.github.io
baseurl:          ''

author:
  name:           'Colleen Smith'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/6cdds/6cdds.github.io
